name: Unit Tests 
 
on:
 workflow_dispatch:
 
jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up ruby env
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true

      - name: Run tests
        run: bundle exec fastlane tests